### ISSUE TITLE
"Keep original sidebearings" making /space zero-width

### ISSUE THREAD

**Issue by ryanbugden** [roboDocs/ScaleFast#15]
I'm not sure if this happens to anyone else, but I've gotten interpolation results where the space glyphs is zero width. My suspicion is that it's related to the "Keep original sidebearings" setting.

**Comment by typemytype** [comment]
yeah there should be probably a check here: https://github.com/roboDocs/ScaleFast/blob/f435ea73140cb2c35e9f1f2db0680de3a4514b64/ScaleFast.roboFontExt/lib/scaleFast.py#L785-L788

as you space has no contours or components, there is no left or right margin... 

this will change the width of character... Im unsure what `KeepSideBearings` means in a contour less glyph?

**Comment by ryanbugden** [comment]
> Im unsure what `KeepSideBearings` means in a contour less glyph?

Yeah, I see the issue here :\ I'm inclined to suggest it maintain the glyph width as opposed to interpolate it. Because without `KeepSideBearings` it would do the opposite. The intention behind `KeepSideBearings` is conservative of spacing, and in most cases the transformation would probably be subtle.

**Comment by typemytype** [comment]
oke :) keep the width for when the leftMargin is None

**Comment by typemytype** [comment]
could you test this? before I touch the version number? 

thanks

**Comment by ryanbugden** [comment]
Can confirm that this works!
